title: Kentish Lodge MSCT Bylaws, Policies and Feedback
baseurl: "/public"
theme: minima
plugins:
  - jekyll-optional-front-matter  # Allows files without YAML headers
collections:
  policies:
    output: true
  bylaws:
    output: true
