title: Kentish Lodge MSCT Bylaws, Policies and Feedback
theme: minima
url: "https://info.kentishlodge.com" # e.g. https://your-org.github.io
baseurl: "" # empty when serving at the root of a custom domain

collections:
  policies:
    output: true
    permalink: /policies/:path/
  bylaws:
    output: true
    permalink: /bylaws/:path/
  announcements:
    output: true
    permalink: /announcements/:path/

defaults:
  - scope:
      path: ""
      type: bylaws
    values:
      layout: item
  - scope:
      path: ""
      type: policies
    values:
      layout: item
  - scope:
      path: ""
      type: announcements
    values:
      layout: item
