title: Kentish Lodge MSCT Bylaws, Policies and Feedback
theme: minima
url: "https://info.kentishlodge.com" # e.g. https://your-org.github.io
baseurl: "/" # if this is a project page, set to "/Kentish-Lodge-MCST-2405" (repo name)

collections:
  policies:
    output: true
    permalink: /policies/:path/
  bylaws:
    output: true
    permalink: /bylaws/:path/
  announcements:
    output: true
    permalink: /announcements/:path/

defaults:
  - scope:
      path: ""
      type: bylaws
    values:
      layout: item
  - scope:
      path: ""
      type: policies
    values:
      layout: item
  - scope:
      path: ""
      type: announcements
    values:
      layout: item
